# docker-compose.yml - Local development and testing
version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
      - API_KEYS=dev-key-123,test-key-456
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost
      - ENABLE_WEBSOCKET=true
      - PUBLIC_READ=true
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GUI Service
  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    ports:
      - "3000:80"
    environment:
      - API_BASE=http://localhost:8080
      - API_KEY=dev-key-123
      - ENABLE_WEBSOCKET=true
    depends_on:
      - api

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
