providers = ["python"]

[variables]
NIXPACKS_SKIP_NODE = "true"

[phases.setup]
# Pick the Python you want; 3.11 is recommended
nixPkgs = ["python311", "pip", "gcc", "gnumake"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python -m uvicorn scripts.production_server:app --host 0.0.0.0 --port ${PORT:-8080}"
