[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "lapack", "blas"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install gunicorn"
]

[phases.build]
cmds = [
    "cd ode_gui_bundle && npm install && npm run build && cd ..",
    "echo 'Build completed'"
]

[start]
cmd = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker scripts.production_server:app --bind 0.0.0.0:${PORT:-8080} --timeout 300"
