# nixpacks.toml - Minimal configuration

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

# Just install Python - Railway will detect Node.js from package.json
[nixpkgs]
packages = ["python311", "python311Packages.pip"]

# Install Python deps
[phases.install]
cmds = ["pip install -r requirements.txt"]

# Build GUI - Railway should auto-detect this
[phases.build]
cmds = [
    "cd ode_gui_bundle && npm ci && npm run build"
]

# Start server
[start]
cmd = "python scripts/production_server.py"
