[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[nixpkgs]
packages = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python3.11 -m pip install --user --upgrade pip",
    "python3.11 -m pip install --user -r requirements.txt"
]

[phases.build]
cmds = [
    "cd ode_gui_bundle && npm ci && npm run build && cd .."
]

[start]
cmd = "python3.11 scripts/production_server.py"
