[build]
# Use the Dockerfile created in this project for building the container.
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Define how Railway checks the service health and manages restarts
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[deploy.env]
# These environment variables configure the FastAPI server and GUI.
ENVIRONMENT = "production"
ENABLE_WEBSOCKET = "true"
PUBLIC_READ = "true"
PORT = "8080"
GUI_BUNDLE_DIR = "ode_gui_bundle/dist"
