[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

# Environment variables
[deploy.env]
ENVIRONMENT = "production"
ENABLE_WEBSOCKET = "true"
PUBLIC_READ = "true"
PORT = "8080"

# GUI bundle directory (where the built React app is located)
GUI_BUNDLE_DIR = "ode_gui_bundle"

# API configuration
ALLOWED_ORIGINS = "https://${{RAILWAY_STATIC_URL}},https://${{RAILWAY_PUBLIC_DOMAIN}}"

# Optional: if you want to use a custom domain
# ALLOWED_ORIGINS = "https://your-custom-domain.com,https://${{RAILWAY_PUBLIC_DOMAIN}}"
