[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "always"

# API Service Configuration
[[services]]
name = "ode-api"
source = "./api"  # Point to your API source directory
[services.build]
builder = "nixpacks"
[services.env]
ENVIRONMENT = "production"
ENABLE_WEBSOCKET = "true"
PUBLIC_READ = "false"
ALLOWED_ORIGINS = "https://${{RAILWAY_STATIC_URL}}"

# GUI Service Configuration  
[[services]]
name = "ode-gui"
source = "./gui"  # Point to your GUI source directory
[services.build]
builder = "nixpacks"
[services.env]
API_BASE = "https://${{RAILWAY_SERVICE_ODE_API_URL}}"
ENABLE_WEBSOCKET = "true"
