[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python scripts/production_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
port = 8000

[[services]]
name = "gui"
port = 8501
startCommand = "streamlit run gui/integrated_interface.py"
