[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd ode_gui_bundle && npm install && npm run build"

[deploy]
startCommand = "python scripts/production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
